### ISSUE TITLE
Plugin does not seem to be using the sonar-project.properties file

### ISSUE THREAD

**Issue by Bhargav-Rao** [aosapps/drone-sonar-plugin#14]
Hi, I'd like to thank you for creating this awesome plugin. I was playing around with it and found it very intuitive to use. I'm facing a small problem, and would like to make sure that it isn't a bug. The documentation mentions:

> The projectKey and projectName of SonarQube project are filled using the full repository name. You could also add a file named sonar-project.properties at the root of your project to specify parameters.

I specified a sonar-project.properties file, but the plugin still seems to use the repository name, instead of the one specified as the project key. The sonar-project.properties file is: 

```
sonar.projectKey=testing-drone-sonar
sonar.projectName=testing-drone-sonar
sonar.sources=src
sonar.language=py
sonar.python.coverage.reportPath=coverage.xml
sonar.python.xunit.reportPath=pytest.xml
```

The .drone.yml file is: 

```yaml
---
kind: pipeline
name: test-drone

type: docker
steps:
- name: deploy
  image: python:3.8
  commands:
    - pip install pipenv
    - pipenv install --dev
    - pipenv run python -m pytest --cov-report=html:htmlcov --cov=src --junitxml=pytest.xml
    - pipenv run python -m coverage xml -i
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
```

And I have my .drone.yml and the sonar-project.properties file at my root. 

Can you take a look at this and let me know if it is a bug,  or if I need to change the configurations in some way? Thanks for your help.
