### ISSUE TITLE
Drone logs don't seem to show that the sonar_host is being read

### ISSUE THREAD

**Issue by fptiangco** [aosapps/drone-sonar-plugin#2]
Thanks for this plugin.
I'm just trying to use this with our newly setup drone, and though I'm sure I have the sonar_host and sonar_token values set correctly in secrets, I'm unable to see in the logs that it's actually being read:

My pipeline section looks like:

```
pipeline:
  code-analysis:
    image: aosapps/drone-sonar-plugin
    settings:
        sonar_host:
          from_secret: sonar_host
        sonar_token:
          from_secret: sonar_token
```

I could just be missing something simple. Thank you.
