### ISSUE TITLE
Why cant specify projectKey and projectName?

### ISSUE THREAD

**Issue by josevavia** [aosapps/drone-sonar-plugin#24]
According to docs:

```
projectKey: DRONE_REPO
projectName: DRONE_REPO
You could also add a file named sonar-project.properties at the root of your project to specify parameters.
```

why not be able to set projectKey and projectName using settings in drone pipeline?

I have a project with a lot of git branches, and I want to send to sonarqube each branch as a different project. With the actual approach, I need to set different settings in sonar-project.properties for each branch to get that.

It would be great if I can set key and project name in the plugin settings, as I have different steps in drone.yml for each branch.

I dont know if there is any technical reason for this

**Comment by josevavia** [comment]
As a solution, I can get it working using following setup:

drone.yml:
```
  - name: sonarqube
    image: aosapps/drone-sonar-plugin
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      usingProperties: true
```

sonar-project.properties (in branch-1):
```
sonar.projectName=Branch 1
sonar.projectKey=com.domain.branch-1
```

sonar-project.properties (in branch-2):
```
sonar.projectName=Branch 2
sonar.projectKey=com.domain.branch-2
```

Anyway, I think it would be great that we can be able to set projectKey and projectName as settings in drone pipeline, something like this:

```
  - name: sonarqube
    image: aosapps/drone-sonar-plugin
    when:
      branch:
        branch-name-1
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      projectKey: com.domain-branch-1
      projectName: Branch 1


  - name: sonarqube
    image: aosapps/drone-sonar-plugin
    when:
      branch:
        branch-name-2
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
      projectKey: com.domain-branch-2
      projectName: Branch 2
```

This way, the configuration is made in the specific step for each branch, and sonar-project.properties is not needed.
