### ISSUE TITLE
cannot add usingProperties: true

### ISSUE THREAD

**Issue by invertium** [aosapps/drone-sonar-plugin#29]
I have a sonar-project.properties file and set the 

```
name: code-analysis
    image: aosapps/drone-sonar-plugin
    settings:
      usingProperties: true
```

However i get:

```
1 | ==> Code Analysis Result:
-- | --
2 | INFO: Scanner configuration file: /bin/sonar-scanner-4.4.0.2170/conf/sonar-scanner.properties
3 | INFO: Project root configuration file: NONE
```
