### ISSUE TITLE
Failed with Drone: Please provide compiled classes of your project with sonar.java.binaries property

### ISSUE THREAD

**Issue by mailbyms** [aosapps/drone-sonar-plugin#30]
```
ERROR: Error during SonarScanner execution
64 | org.sonar.java.AnalysisException: Please provide compiled classes of your project with sonar.java.binaries property
65 | at org.sonar.java.JavaClasspath.init(JavaClasspath.java:64)
66 | at org.sonar.java.AbstractJavaClasspath.getElements(AbstractJavaClasspath.java:280)
67 | at
```

I use the lastest plugin image, and my `.drone.yml` just like this: 
```
  - name: sonar
    image: aosapps/drone-sonar-plugin
    pull: if-not-exists
    settings:
      sonar_host:
        from_secret: sonar_host
      sonar_token:
        from_secret: sonar_token
    when:
      event:
        - push
```

Please help.
